package com.undebugged.mylyn.tbg.core;
/**
 * Exception generated by the {@link TBGService}
 * @author Guido Grazioli
 */
public class TBGServiceException extends Exception {

    private static final long serialVersionUID = -1;

    /**
     * Constructor.
     * @param cause
     */
    public TBGServiceException(Throwable cause) {
        super(cause);
    }

    public TBGServiceException(String message) {
        super(message);
    }

    public TBGServiceException(String message, Throwable cause) {
        super(message, cause);
    }
}